export const manifest = {
  manifest_version:3,
  name:'__MSG_app_title__',
  version:'0.3.0',
  default_locale:'en',
  description:'__MSG_app_desc__',
  minimum_chrome_version:'116',
  permissions:['activeTab','tabs','scripting','storage','downloads','sidePanel','webRequest','offscreen','alarms','declarativeNetRequestWithHostAccess'],
  host_permissions:['http://*/*','https://*/*'],
  background:{service_worker:'background.js',type:'module'},
  action:{default_title:'__MSG_action_title__',default_icon:{16:'icons/16.png',32:'icons/32.png'}},
  side_panel:{default_path:'sidepanel.html'},
  icons:{16:'icons/16.png',32:'icons/32.png',48:'icons/48.png',128:'icons/128.png'},
  content_security_policy:{extension_pages:"script-src 'self'; object-src 'none'"},
};
